name : Deploy Futsal Frontend 

on : 
  push :
    branches :
      - multi

jobs :
  deploy :
    runs-on : ubuntu-latest

    steps :
      - name : Checkout Code
        uses : action/checkout@v4

      - name : Deploy via SSH
        uses : appleboy/ssh-action@v1.0.3
        with :
          host : ${{ secrets.SSH_HOST }}
          username : root
          key : ${{ secrets.SSH_KEY }} 
          script :
            cd /home/ubuntu/projects/khelkud/futsal-fe
            git pull
            docker compose -f docker-compose.yml up -d --build --force-recreate






